
import 'package:beautify/core/routes/route_names.dart';
import 'package:beautify/ui/view/create/create.dart';
import 'package:beautify/ui/view/homepage/home.dart';
import 'package:beautify/ui/view/onboarding/onboarding.dart';
import 'package:beautify/ui/view/splashscreen/splashscreen.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';


class RouteGenerator {
  ///Routes are generated by this function
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {

      ///All views are registered here with appropriate page transition in this format
      case RouteNames.splashScreen:
        return CupertinoPageRoute(builder: (context) => SplashScreen());
        case RouteNames.onboarding:
        return CupertinoPageRoute(builder: (context) => Onboarding());
        case RouteNames.home:
        return CupertinoPageRoute(builder: (context) => HomeScreen());
        case RouteNames.create:
        return CupertinoPageRoute(builder: (context) => ChartScreen());
        
        break;
      
      default:
        return _errorRoute();
    }
  }

  ///Custom error route to ease debugging of unregistered routes
  static Route<dynamic> _errorRoute() {
    return CupertinoPageRoute(
      builder: (context) => Scaffold(
          appBar: AppBar(
              title: Text(
            'Page not found',
            style: TextStyle(color: Colors.red),
          )),
          body: Center(
            child: Text(
              'Error! Page not found',
              style: TextStyle(color: Colors.red),
            ),
          )),
    );
  }
}
